[package]
name = "advent-of-code-2023-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "aoc2023"
path = "src/main.rs"

[dependencies]
